### PR TITLE
Fix root path for export on krita4.3

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
In the way that the name of the root node is replaced by 'export' on the plugin does not work with krita 4.3, that causes that the exports where created in the same folder of the kra file, instead of in a folder. That was not a big issue _per se_ but it also broke the COA exports.
This patch is intended to fix the bug without breaking backward compatibility.

**Comment by NathanLovato** [comment]
Thanks for your contribution!

Here's an issue remaining:

Screenshot from 2020-05-30 07-59-13

Exports like so:

Screenshot from 2020-05-30 07-58-14

It should all be in `export/`, and 3.png should be in `export/Layer_4/Layer_5/3.png`

Here's the file for testing:

[test.zip](https://github.com/GDQuest/krita-batch-exporter/files/4705737/test.zip)

**Comment by NathanLovato** [comment]
We should start to keep some test document and maybe have a regression test?

**Comment by leiserfg** [comment]
Now everything is created inside of the export folder, anyway I don't know if everything is working fine with the COA export because I don't know how it should work for it.
I replaced the use of `os.path` with `pathlib` to make the implementation easier to read and to avoid  doing manual path separation/joins because it can be problematic on windows and I have no windows to test.

**Comment by NathanLovato** [comment]
@Larpon, do you have a sample krita file we could use to test the exporter with COA tools? A simple file with a real-world character with the correct JSON/export we could keep in the repo for automated testing would be great, that way we can try exporting from new versions of the add-on to COA tools and see if it breaks.

**Comment by Larpon** [comment]
@NathanLovato - yes, sure I'll cook something up

**Comment by Larpon** [comment]
@NathanLovato 

Test files: #44 
Fix for recent changes: #43

**Comment by NathanLovato** [comment]
Just tested everything, looking great, thanks much!

**Comment by NathanLovato** [comment]
I'm merging manually to fix conflicts

**Comment by leiserfg** [comment]
IMHO we should avoid using `os.path.sep` at all because it does not work that well in windows (there both `/` and `\` are valid). That's why I'm using `libpath`.

**Comment by NathanLovato** [comment]
Merged manually in 208239547eca6956eecd7b6cf70468ccee8ffcbb

**Comment by NathanLovato** [comment]
Ah, I hadn't paid attention. @Larpon is there any reason you're not using `os.path.join`? @leiserfg is there something pathlib does that os.path can't handle well?

**Comment by NathanLovato** [comment]
Forget my previous comments, re-reading the code and thread I see I should've drank some more coffee this morning. I'll clean up the changes. Sorry for the hasty merges!

**Comment by NathanLovato** [comment]
Done, should be all good now. Thanks for your contribution!

**Comment by leiserfg** [comment]
Nathan, I have another idea, the last one :smile:  we should expose a way for allowing the user to use *nearest-neighbor* (NN) as interpolation algorithm, most of the time you want smooth interpolation, but for those doing pixel art is better to use *NN* for up-scaling.

**Pull request merged**
